MODEL:
  TYPE: generalized_rcnn
  SUBTYPE: 3
  USE_OVLP_FILTER: False
  USE_FREQ_BIAS: True
  NO_FC7_RELU: True
  CONV_BODY: FPN.fpn_ResNet101_conv5_body
  FASTER_RCNN: True
  USE_SEPARATE_SO_SCORES: True
  NORM_SCALE: 10.0
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  BASE_LR: 0.01
  GAMMA: 0.1
  MAX_ITER: 10039452
  STEPS: [0, 1000000]
  TYPE: Adam # SGD
  BACKBONE_LR_SCALAR: 0.01
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
RESNETS:
  COCO_PRETRAINED_WEIGHTS: 'detectron_model/X-101-64x4d.pkl'
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_transformation
  NUM_GROUPS: 64
  WIDTH_PER_GROUP: 4
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.roi_2avg_pool
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  SCALES: (200,)
  MAX_SIZE: 256
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000
TEST:
  FORCE_JSON_DATASET_EVAL: True
  SCALE: 200
  MAX_SIZE: 256
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 2000
  RPN_POST_NMS_TOP_N: 2000
